// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject.Api.Data;

#nullable disable

namespace MyProject.Api.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyProject.Api.Data.Entities.Noodle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Noodles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://github.com/Chenglongt/MyProject/blob/test-and-add-new-attachments/Tonkotsu.png",
                            Name = "Tonkotsu",
                            Price = 14.0
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://github.com/Chenglongt/MyProject/blob/test-and-add-new-attachments/Geki%20Kara.png",
                            Name = "Geki Kara",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://github.com/Chenglongt/MyProject/blob/test-and-add-new-attachments/Chilli%20Chicken.png",
                            Name = "Chilli Chicken",
                            Price = 13.5
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://github.com/Chenglongt/MyProject/blob/test-and-add-new-attachments/Chilli%20Tiger%20Prawn.png",
                            Name = "Chilli Tiger Prawn",
                            Price = 14.949999999999999
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://github.com/Chenglongt/MyProject/blob/test-and-add-new-attachments/Tokyo.png",
                            Name = "Tokyo ",
                            Price = 14.5
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://github.com/Chenglongt/MyProject/blob/test-and-add-new-attachments/Japanese%20Mushroom%20Miso.png",
                            Name = "Japanese Mushroom Miso",
                            Price = 11.949999999999999
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://github.com/Chenglongt/MyProject/blob/test-and-add-new-attachments/Japanese%20Mushroom.png",
                            Name = "Japanese Mushroom",
                            Price = 11.949999999999999
                        });
                });

            modelBuilder.Entity("MyProject.Api.Data.Entities.NoodleOption", b =>
                {
                    b.Property<int>("NoodleId")
                        .HasColumnType("int");

                    b.Property<string>("Flavor")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Topping")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("NoodleId", "Flavor", "Topping");

                    b.ToTable("NoodleOptions");

                    b.HasData(
                        new
                        {
                            NoodleId = 1,
                            Flavor = "Default",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 1,
                            Flavor = "Extra Spicy",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 1,
                            Flavor = "Extra Solt",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 1,
                            Flavor = "Default",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 1,
                            Flavor = "Extra Spicy",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 1,
                            Flavor = "Extra Solt",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 1,
                            Flavor = "Default",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 1,
                            Flavor = "Extra Spicy",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 1,
                            Flavor = "Extra Solt",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 1,
                            Flavor = "Default",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 1,
                            Flavor = "Extra Spicy",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 1,
                            Flavor = "Extra Solt",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 2,
                            Flavor = "Default",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 2,
                            Flavor = "Extra Spicy",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 2,
                            Flavor = "Extra Solt",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 2,
                            Flavor = "Default",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 2,
                            Flavor = "Extra Spicy",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 2,
                            Flavor = "Extra Solt",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 2,
                            Flavor = "Default",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 2,
                            Flavor = "Extra Spicy",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 2,
                            Flavor = "Extra Solt",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 2,
                            Flavor = "Default",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 2,
                            Flavor = "Extra Spicy",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 2,
                            Flavor = "Extra Solt",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 3,
                            Flavor = "Default",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 3,
                            Flavor = "Extra Spicy",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 3,
                            Flavor = "Extra Solt",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 3,
                            Flavor = "Default",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 3,
                            Flavor = "Extra Spicy",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 3,
                            Flavor = "Extra Solt",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 3,
                            Flavor = "Default",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 3,
                            Flavor = "Extra Spicy",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 3,
                            Flavor = "Extra Solt",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 3,
                            Flavor = "Default",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 3,
                            Flavor = "Extra Spicy",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 3,
                            Flavor = "Extra Solt",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 4,
                            Flavor = "Default",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 4,
                            Flavor = "Extra Spicy",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 4,
                            Flavor = "Extra Solt",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 4,
                            Flavor = "Default",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 4,
                            Flavor = "Extra Spicy",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 4,
                            Flavor = "Extra Solt",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 4,
                            Flavor = "Default",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 4,
                            Flavor = "Extra Spicy",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 4,
                            Flavor = "Extra Solt",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 4,
                            Flavor = "Default",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 4,
                            Flavor = "Extra Spicy",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 4,
                            Flavor = "Extra Solt",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 5,
                            Flavor = "Default",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 5,
                            Flavor = "Extra Spicy",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 5,
                            Flavor = "Extra Solt",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 5,
                            Flavor = "Default",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 5,
                            Flavor = "Extra Spicy",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 5,
                            Flavor = "Extra Solt",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 5,
                            Flavor = "Default",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 5,
                            Flavor = "Extra Spicy",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 5,
                            Flavor = "Extra Solt",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 5,
                            Flavor = "Default",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 5,
                            Flavor = "Extra Spicy",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 5,
                            Flavor = "Extra Solt",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 6,
                            Flavor = "Default",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 6,
                            Flavor = "Extra Spicy",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 6,
                            Flavor = "Extra Solt",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 6,
                            Flavor = "Default",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 6,
                            Flavor = "Extra Spicy",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 6,
                            Flavor = "Extra Solt",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 6,
                            Flavor = "Default",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 6,
                            Flavor = "Extra Spicy",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 6,
                            Flavor = "Extra Solt",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 6,
                            Flavor = "Default",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 6,
                            Flavor = "Extra Spicy",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 6,
                            Flavor = "Extra Solt",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 7,
                            Flavor = "Default",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 7,
                            Flavor = "Extra Spicy",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 7,
                            Flavor = "Extra Solt",
                            Topping = "Egg"
                        },
                        new
                        {
                            NoodleId = 7,
                            Flavor = "Default",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 7,
                            Flavor = "Extra Spicy",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 7,
                            Flavor = "Extra Solt",
                            Topping = "Pork Belly"
                        },
                        new
                        {
                            NoodleId = 7,
                            Flavor = "Default",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 7,
                            Flavor = "Extra Spicy",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 7,
                            Flavor = "Extra Solt",
                            Topping = "Vegetable"
                        },
                        new
                        {
                            NoodleId = 7,
                            Flavor = "Default",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 7,
                            Flavor = "Extra Spicy",
                            Topping = "Chilli Chicken"
                        },
                        new
                        {
                            NoodleId = 7,
                            Flavor = "Extra Solt",
                            Topping = "Chilli Chicken"
                        });
                });

            modelBuilder.Entity("MyProject.Api.Data.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerIdAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("OrderAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MyProject.Api.Data.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Flavor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("NoodleId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Topping")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MyProject.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyProject.Api.Data.Entities.NoodleOption", b =>
                {
                    b.HasOne("MyProject.Api.Data.Entities.Noodle", "Noodle")
                        .WithMany("Options")
                        .HasForeignKey("NoodleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Noodle");
                });

            modelBuilder.Entity("MyProject.Api.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("MyProject.Api.Data.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MyProject.Api.Data.Entities.Noodle", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("MyProject.Api.Data.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
